"""
Auto-generated by data_extract.py from excelcell.csv.

Implements ModalSurcharge(PayFreq) exactly as the Excel formula in Calculation!E12:
  =IF(PayFreq=2,2%,IF(PayFreq=4,3%,IF(PayFreq=12,5%,0)))
"""

from __future__ import annotations


EXCEL_E12_FORMULA = '=IF(PayFreq=2,2%,IF(PayFreq=4,3%,IF(PayFreq=12,5%,0)))'
_MODAL_MAP = {2: 0.02, 4: 0.03, 12: 0.05}


def ModalSurcharge(PayFreq: int) -> float:
    """
    Modal surcharge for payment frequency.

    Mirrors the nested IF in Excel cell Calculation!E12.
    """
    try:
        pf = int(PayFreq)
    except Exception as e:
        raise TypeError("PayFreq must be convertible to int") from e
    return float(_MODAL_MAP.get(pf, 0.0))
